// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/github.get').default>>>>
    }
    '/api/github/contributions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/github/contributions.get').default>>>>
    }
    '/api/rss.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rss.xml.get').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.get').default>>>>
    }
    '/api/sitemap.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sitemap.xml.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.8_better-sqlite3@12.11.1_db0@0.3.4_better-sqlite3@12.11.1__esbu_9401d48088215084f584dd55cae08eab/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.3_vite@7.3.6_jiti@2.7.0_lightningcss@1.32.0_terser@5.49._3b21eaeda50cce165ee7d908f2fe08d4/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_content/projects_en/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/projects_es/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/experience_en/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/experience_es/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/blog_en/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/blog_es/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/info/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__nuxt_content/projects_en/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/projects_es/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/experience_en/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/experience_es/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/blog_en/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/blog_es/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/info/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.0_@valibot+to-json-schema@1.7.1_valibot@1.4.2_typescript@5.9.3___bet_d813838a7756b496e7275e2811f16b06/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@1.11.0_db0@0.3.4_better-sqlite3@12.11.1__ioredis@5.11.1_magicast@0.5.3_srvx@0.11.21/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}