language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '12.13.1'
git:
  depth: 3
before_script:
  - "npm i -g gatsby-cli"
  - "yarn"
script:
  - gatsby build --prefix-paths && gh-pages -d public
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
