sudo: false

language: node_js

node_js:
 - "8"
 - "10"
 - "12"

cache:
  yarn: true
  directories:
    - node_modules

before_script :
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s
 - export PATH=$HOME/.yarn/bin:$PATH
 - yarn install

script:
 - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
